package com.pay.app.domain;

public enum DeductionCode {
    BENEFITS_MEDICAL, BENEFITS_401K, BENEFITS_FSA, BENEFITS_LIFE_INSURANCE,
    BENEFITS_OTHER1, BENEFITS_OTHER2, BENEFITS_OTHER3, BENEFITS_OTHER4, BENEFITS_OTHER5
}
