version: '2'
services:
    payapp-app:
        image: payapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://payapp-mysql:3306/payapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8089:8089
    payapp-mysql:
        extends:
            file: mysql.yml
            service: payapp-mysql
